### ISSUE TITLE
catkin build failed at fub_navigation

### ISSUE THREAD

**Issue by EmilianoGCH** [AutoMiny/AutoMiny#9]
Hello 

I tried catkin build on Ubuntu 18.04 and kernel 5.8.5
but I get 26 succeed packages out of 30
2 failed 
2 abandoned

Failed packages are:
-arduino_communication
-fub_navigation

Error messages:
`Errors     << arduino_communication:cmake /home/egalvan/git-dev/autominy/catkin_ws/logs/arduino_communication/build.cmake.006.log
ImportError: "from catkin_pkg.package import parse_package" failed: No module named catkin_pkg.package
Make sure that you have installed "catkin_pkg", it is up to date and on the PYTHONPATH.
CMake Error at /opt/ros/melodic/share/catkin/cmake/safe_execute_process.cmake:11 (message):
  execute_process(/home/egalvan/miniconda3/envs/python27/bin/python2
  "/opt/ros/melodic/share/catkin/cmake/parse_package_xml.py"
  "/opt/ros/melodic/share/catkin/cmake/../package.xml"
  "/home/egalvan/git-dev/autominy/catkin_ws/build/arduino_communication/catkin/catkin_generated/version/package.cmake")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/catkin_package_xml.cmake:74 (safe_execute_process)
  /opt/ros/melodic/share/catkin/cmake/all.cmake:168 (_catkin_package_xml)
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:11 (find_package)

cd /home/egalvan/git-dev/autominy/catkin_ws/build/arduino_communication; catkin build --get-env arduino_communication | catkin env -si  /usr/bin/cmake /home/egalvan/git-dev/autominy/catkin_ws/src/arduino_communication --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/egalvan/git-dev/autominy/catkin_ws/devel/.private/arduino_communication -DCMAKE_INSTALL_PREFIX=/home/egalvan/git-dev/autominy/catkin_ws/install; cd -
`
Errors     << fub_navigation:cmake /home/egalvan/git-dev/autominy/catkin_ws/logs/fub_navigation/build.cmake.016.log
Traceback (most recent call last):
  File "/opt/ros/melodic/share/catkin/cmake/order_paths.py", line 43, in <module>
    main()
  File "/opt/ros/melodic/share/catkin/cmake/order_paths.py", line 31, in main
    ordered_paths = order_paths(args.paths_to_order, spaces)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/workspaces.py", line 85, in order_paths
    if _is_equal_or_in_parents(prefix, path):
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/workspaces.py", line 95, in _is_equal_or_in_parents
    dir_ = os.path.normcase(os.path.realpath(dir_))
  File "/usr/lib/python2.7/posixpath.py", line 382, in realpath
    path, ok = _joinrealpath('', filename, {{}})
  File "/usr/lib/python2.7/posixpath.py", line 407, in _joinrealpath
    if not islink(newpath):
  File "/usr/lib/python2.7/posixpath.py", line 135, in islink
    st = os.lstat(path)
TypeError: lstat() argument 1 must be encoded string without null bytes, not str
CMake Error at /opt/ros/melodic/share/catkin/cmake/safe_execute_process.cmake:11 (message):

  execute_process(/home/egalvan/git-dev/autominy/catkin_ws/build/fub_navigation/catkin_generated/env_cached.sh
  "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/order_paths.py"
  "/home/egalvan/git-dev/autominy/catkin_ws/build/fub_navigation/catkin_generated/ordered_paths.cmake"
  "--paths-to-order" "/opt/ros/melodic/include" "/usr/include"
  "/opt/ros/melodic/share/xmlrpcpp/cmake/../../../include/xmlrpcpp"
  "/home/egalvan/git-dev/autominy/catkin_ws/devel/.private/autominy_msgs/include"
  "--prefixes"
  "/home/egalvan/git-dev/autominy/catkin_ws/devel/.private/fub_navigation"
  "/home/egalvan/git-dev/autominy/catkin_ws/devel" "/opt/ros/melodic")
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/melodic/share/catkin/cmake/list_insert_in_workspace_order.cmake:26 (safe_execute_process)
  /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:108 (list_insert_in_workspace_order)
  CMakeLists.txt:10 (find_package)

cd /home/egalvan/git-dev/autominy/catkin_ws/build/fub_navigation; catkin build --get-env fub_navigation | catkin env -si  /usr/bin/cmake /home/egalvan/git-dev/autominy/catkin_ws/src/fub_navigation --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/egalvan/git-dev/autominy/catkin_ws/devel/.private/fub_navigation -DCMAKE_INSTALL_PREFIX=/home/egalvan/git-dev/autominy/catkin_ws/install; cd -

Hope you can help

I already installed python27 on anaconda enviroment

**Comment by EmilianoGCH** [comment]
- First I updated and upgrade packages
- then reinstall python-rosdep
- Erase CMameCache.txt
- If there are still problems with some packages just delete directories of the packages inside build folder
